### ISSUE TITLE
pydaymet.get_bygeom() appears to be broken regardless of inputs?

### ISSUE THREAD

**Issue by xaviernogueira** [hyriver/pydaymet#58]
**What happened**:
I attempted to use `pydaymet.get_bygeom()` using the example included in the documentation [here](https://docs.hyriver.io/readme/pydaymet.html), yet regardless of how I alter the inputs a null return seems to propagate the error. I tried with different AOIs as well with no change in outcome.

**Input code:**
```python
import pydaymet
hi_ext = (-160.3055, 17.9539, -154.7715, 23.5186)
hi = pydaymet.get_bygeom(hi_ext, 2010, variables="prcp", region="hi", time_scale="annual")
```

**Environment**: I only installed `pydaymet`, without installing any of the other components of hyrivers. Additinally, I verified that `netcdf4` was already pip installed (it was).

Hoping to get some help! Looking to build this into open-source software, but will need more confidence in the dependability. 

**Full error traceback:**
```
-------------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\scipy_.py:102, in _open_scipy_netcdf(filename, mode, mmap, version)
    101 try:
--> 102     return scipy.io.netcdf_file(filename, mode=mode, mmap=mmap, version=version)
    103 except TypeError as e:  # netcdf3 message is obscure in this case

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\scipy\io\_netcdf.py:277, in netcdf_file.__init__(self, filename, mode, mmap, version, maskandscale)
    276 if mode in 'ra':
--> 277     self._read()

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\scipy\io\_netcdf.py:598, in netcdf_file._read(self)
    597 if not magic == b'CDF':
--> 598     raise TypeError("Error: %s is not a valid NetCDF 3 file" %
    599                     self.filename)
    600 self.__dict__['version_byte'] = frombuffer(self.fp.read(1), '>b')[0]

TypeError: Error: None is not a valid NetCDF 3 file

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In [41], line 2
      1 hi_ext = (-160.3055, 17.9539, -154.7715, 23.5186)
----> 2 hi = pydaymet.get_bygeom(hi_ext, 2010, variables="prcp", region="hi", time_scale="annual")

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\pydaymet\pydaymet.py:411, in get_bygeom(geometry, dates, crs, variables, region, time_scale, pet, pet_params, snow, snow_params, ssl)
    400 urls, kwds = zip(
    401     *_gridded_urls(
    402         daymet.time_codes[time_scale],
   (...)
    407     )
    408 )
    410 try:
--> 411     clm: xr.Dataset = xr.open_mfdataset(
    412         (  # type: ignore
    413             io.BytesIO(r)
    414             for r in ar.retrieve_binary(urls, request_kwds=kwds, max_workers=MAX_CONN, ssl=ssl)
    415         ),
    416         engine="scipy",
    417         coords="minimal",
    418     )
    419 except ValueError as ex:
    420     msg = (
    421         "The service did NOT process your request successfully. "
    422         + "Check your inputs and try again."
    423     )

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\api.py:972, in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)
    969     open_ = open_dataset
    970     getattr_ = getattr
--> 972 datasets = [open_(p, **open_kwargs) for p in paths]
    973 closers = [getattr_(ds, "_close") for ds in datasets]
    974 if preprocess is not None:

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\api.py:972, in <listcomp>(.0)
    969     open_ = open_dataset
    970     getattr_ = getattr
--> 972 datasets = [open_(p, **open_kwargs) for p in paths]
    973 closers = [getattr_(ds, "_close") for ds in datasets]
    974 if preprocess is not None:

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\api.py:531, in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, backend_kwargs, **kwargs)
    519 decoders = _resolve_decoders_kwargs(
    520     decode_cf,
    521     open_backend_dataset_parameters=backend.open_dataset_parameters,
   (...)
    527     decode_coords=decode_coords,
    528 )
    530 overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 531 backend_ds = backend.open_dataset(
    532     filename_or_obj,
    533     drop_variables=drop_variables,
    534     **decoders,
    535     **kwargs,
    536 )
    537 ds = _dataset_from_backend_dataset(
    538     backend_ds,
    539     filename_or_obj,
   (...)
    547     **kwargs,
    548 )
    549 return ds

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\scipy_.py:279, in ScipyBackendEntrypoint.open_dataset(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, mode, format, group, mmap, lock)
    261 def open_dataset(
    262     self,
    263     filename_or_obj,
   (...)
    275     lock=None,
    276 ):
    278     filename_or_obj = _normalize_path(filename_or_obj)
--> 279     store = ScipyDataStore(
    280         filename_or_obj, mode=mode, format=format, group=group, mmap=mmap, lock=lock
    281     )
    283     store_entrypoint = StoreBackendEntrypoint()
    284     with close_on_error(store):

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\scipy_.py:154, in ScipyDataStore.__init__(self, filename_or_obj, mode, format, group, mmap, lock)
    146     manager = CachingFileManager(
    147         _open_scipy_netcdf,
    148         filename_or_obj,
   (...)
    151         kwargs=dict(mmap=mmap, version=version),
    152     )
    153 else:
--> 154     scipy_dataset = _open_scipy_netcdf(
    155         filename_or_obj, mode=mode, mmap=mmap, version=version
    156     )
    157     manager = DummyFileManager(scipy_dataset)
    159 self._manager = manager

File ~\Miniconda3\envs\fcpgtools\lib\site-packages\xarray\backends\scipy_.py:113, in _open_scipy_netcdf(filename, mode, mmap, version)
    106     msg = """
    107     If this is a NetCDF4 file, you may need to install the
    108     netcdf4 library, e.g.,
    109 
    110     $ pip install netcdf4
    111     """
    112     errmsg += msg
--> 113     raise TypeError(errmsg)
    114 else:
    115     raise

TypeError: Error: None is not a valid NetCDF 3 file
            If this is a NetCDF4 file, you may need to install the
            netcdf4 library, e.g.,

            $ pip install netcdf4
```

**Comment by cheginit** [comment]
Thanks for reporting the issue.

Daymet updated their dataset (called Daymet v4 R1) a couple of days ago due to some issues and as a result they had to change the URL of their server. I have fixed this issue in `pydaymet` but still haven't released a new version. I will release a new version soon.

**Comment by cheginit** [comment]
In the meanwhile, you can update `pydaymet` from the repo and work with it until the new version is released:

```bash
pip install git+https://github.com/hyriver/pydaymet
```

**Comment by xaviernogueira** [comment]
Thanks for the quick response @cheginit!  Mind closing the issue when you release the version? Until then I'll just pull down from github for development.

**Comment by cheginit** [comment]
Sure!

**Comment by cheginit** [comment]
Just released a new version!

**Comment by Flash-Of-Thunder** [comment]
Hello,

Also getting some interesting errors recently and wondering if it is related. I'm trying to download ~1000 basins but having errors pop up for many of them. Here is an example:

My pydaymet seems to be up to date:
![image](https://user-images.githubusercontent.com/94713715/201747219-bc3588cf-0638-4088-8b3b-8804997e3795.png)

`
from pynhd import NLDI
import pydaymet as daymet

dates = ('2008-01-01', '2021-12-31')
basin = "01531500"

geometry = NLDI().get_basins(basin).geometry[0]    
raw_daymet = daymet.get_bygeom(geometry, dates, pet="hargreaves_samani")
raw_daymet.to_netcdf(f"{output_folder_raw}/{basin}.nc",mode = "w")
raw_daymet.close()
`

`
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
Cell In [2], line 43
     40 basin = "01531500"
     42 geometry = NLDI().get_basins(basin).geometry[0]    
---> 43 raw_daymet = daymet.get_bygeom(geometry, dates, pet="hargreaves_samani")
     44 raw_daymet.to_netcdf(f"{output_folder_raw}/{basin}.nc",mode = "w")
     45 raw_daymet.close()

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/pydaymet/pydaymet.py:467, in get_bygeom(geometry, dates, crs, variables, region, time_scale, pet, pet_params, snow, snow_params, ssl)
    453 urls, kwds = zip(
    454     *_gridded_urls(
    455         daymet.time_codes[time_scale],
   (...)
    460     )
    461 )
    463 try:
    464     clm: xr.Dataset = xr.open_mfdataset(
    465         (  # type: ignore
    466             io.BytesIO(r)
--> 467             for r in ar.retrieve_binary(urls, request_kwds=kwds, max_workers=MAX_CONN, ssl=ssl)
    468         ),
    469         engine="scipy",
    470         coords="minimal",
    471     )
    472 except ValueError as ex:
    473     msg = (
    474         "The service did NOT process your request successfully. "
    475         + "Check your inputs and try again."
    476     )

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/async_retriever/async_retriever.py:496, in retrieve_binary(urls, request_kwds, request_method, max_workers, cache_name, timeout, expire_after, ssl, disable)
    454 def retrieve_binary(
    455     urls: Sequence[StrOrURL],
    456     request_kwds: Optional[Sequence[Dict[str, Any]]] = None,
   (...)
    463     disable: bool = False,
    464 ) -> List[bytes]:
    465     r"""Send async requests and get the response as ``bytes``.
    466 
    467     Parameters
   (...)
    494         List of responses in the order of input URLs.
    495     """
--> 496     resp: List[bytes] = retrieve(  # type: ignore
    497         urls,
    498         "binary",
    499         request_kwds,
    500         request_method,
    501         max_workers,
    502         cache_name,
    503         timeout,
    504         expire_after,
    505         ssl,
    506         disable,
    507     )
    508     return resp

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/async_retriever/async_retriever.py:246, in retrieve(urls, read_method, request_kwds, request_method, max_workers, cache_name, timeout, expire_after, ssl, disable)
    242 chunked_reqs = tlz.partition_all(max_workers, inp.url_kwds)
    244 results = (loop.run_until_complete(session(url_kwds=c)) for c in chunked_reqs)
--> 246 resp = [r for _, r in sorted(tlz.concat(results))]
    247 if new_loop:
    248     loop.close()

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/async_retriever/async_retriever.py:244, in <genexpr>(.0)
    230 session = tlz.partial(
    231     async_session,
    232     read=inp.read_method,
   (...)
    239     disable=disable,
    240 )
    242 chunked_reqs = tlz.partition_all(max_workers, inp.url_kwds)
--> 244 results = (loop.run_until_complete(session(url_kwds=c)) for c in chunked_reqs)
    246 resp = [r for _, r in sorted(tlz.concat(results))]
    247 if new_loop:

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/nest_asyncio.py:90, in _patch_loop.<locals>.run_until_complete(self, future)
     87 if not f.done():
     88     raise RuntimeError(
     89         'Event loop stopped before Future completed.')
---> 90 return f.result()

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception
    202 return self._result

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/asyncio/tasks.py:256, in Task.__step(***failed resolving arguments***)
    252 try:
    253     if exc is None:
    254         # We use the `send` method directly, because coroutines
    255         # don't have `__iter__` and `__next__` methods.
--> 256         result = coro.send(None)
    257     else:
    258         result = coro.throw(exc)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/async_retriever/async_retriever.py:92, in async_session(url_kwds, read, r_kwds, request_method, cache_name, timeout, expire_after, ssl, disable)
     87 request_func = getattr(session, request_method.lower())
     88 tasks = (
     89     utils.retriever(uid, url, kwds, request_func, read, r_kwds)
     90     for uid, url, kwds in url_kwds
     91 )
---> 92 return await asyncio.gather(*tasks)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/asyncio/tasks.py:328, in Task.__wakeup(self, future)
    326 def __wakeup(self, future):
    327     try:
--> 328         future.result()
    329     except BaseException as exc:
    330         # This may also be a cancellation.
    331         self.__step(exc)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/asyncio/tasks.py:258, in Task.__step(***failed resolving arguments***)
    256         result = coro.send(None)
    257     else:
--> 258         result = coro.throw(exc)
    259 except StopIteration as exc:
    260     if self._must_cancel:
    261         # Task is cancelled right before coro stops.

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/async_retriever/utils.py:62, in retriever(uid, url, s_kwds, session, read_type, r_kwds)
     30 async def retriever(
     31     uid: int,
     32     url: StrOrURL,
   (...)
     36     r_kwds: Dict[str, None],
     37 ) -> Tuple[int, Union[str, Awaitable[Union[str, bytes, Dict[str, Any]]]]]:
     38     """Create an async request and return the response as binary.
     39 
     40     Parameters
   (...)
     60         The retrieved response as binary.
     61     """
---> 62     async with session(url, **s_kwds) as response:
     63         try:
     64             return uid, await getattr(response, read_type)(**r_kwds)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp/client.py:1141, in _BaseRequestContextManager.__aenter__(self)
   1140 async def __aenter__(self) -> _RetType:
-> 1141     self._resp = await self._coro
   1142     return self._resp

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/forge/_revision.py:322, in Revision.__call__.<locals>.inner(*args, **kwargs)
    318 @functools.wraps(callable)
    319 async def inner(*args, **kwargs):
    320     # pylint: disable=E1102, not-callable
    321     mapped = inner.__mapper__(*args, **kwargs)
--> 322     return await callable(*mapped.args, **mapped.kwargs)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp_client_cache/session.py:62, in CacheMixin._request(self, method, str_or_url, expire_after, **kwargs)
     60 actions.update_from_response(new_response)
     61 if await self.cache.is_cacheable(new_response, actions):
---> 62     await self.cache.save_response(new_response, actions.key, actions.expires)
     63 return set_response_defaults(new_response)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp_client_cache/backends/base.py:168, in CacheBackend.save_response(self, response, cache_key, expires)
    160 """Save a response to the cache
    161 
    162 Args:
   (...)
    165     expires: Expiration time to set for the response
    166 """
    167 cache_key = cache_key or self.create_key(response.method, response.url)
--> 168 cached_response = await CachedResponse.from_client_response(response, expires)
    169 await self.responses.write(cache_key, cached_response)
    171 # Alias any redirect requests to the same cache key

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp_client_cache/response.py:86, in CachedResponse.from_client_response(cls, client_response, expires)
     84 # Read response content, and reset StreamReader on original response
     85 if not client_response._released:
---> 86     await client_response.read()
     87 response._body = client_response._body
     88 client_response.content = CachedStreamReader(client_response._body)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp/client_reqrep.py:1037, in ClientResponse.read(self)
   1035 if self._body is None:
   1036     try:
-> 1037         self._body = await self.content.read()
   1038         for trace in self._traces:
   1039             await trace.send_response_chunk_received(
   1040                 self.method, self.url, self._body
   1041             )

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp/streams.py:375, in StreamReader.read(self, n)
    373 blocks = []
    374 while True:
--> 375     block = await self.readany()
    376     if not block:
    377         break

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp/streams.py:397, in StreamReader.readany(self)
    393 # TODO: should be `if` instead of `while`
    394 # because waiter maybe triggered on chunk end,
    395 # without feeding any data
    396 while not self._buffer and not self._eof:
--> 397     await self._wait("readany")
    399 return self._read_nowait(-1)

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp/streams.py:304, in StreamReader._wait(self, func_name)
    302 if self._timer:
    303     with self._timer:
--> 304         await waiter
    305 else:
    306     await waiter

File /work/zhilyaev_umass_edu/.conda/envs/python3_9/lib/python3.9/site-packages/aiohttp/helpers.py:720, in TimerContext.__exit__(self, exc_type, exc_val, exc_tb)
    717     self._tasks.pop()
    719 if exc_type is asyncio.CancelledError and self._cancelled:
--> 720     raise asyncio.TimeoutError from None
    721 return None

TimeoutError: 
`

Another time running this same code I got:

`OperationalError: database is locked`

Thoughts? Many thanks!

**Comment by cheginit** [comment]
This error is related to a corrupt cache file. You can remove the cache folder in your current working directory and retry.

For large requests, you might end up getting a timeout error once in a while since the server might get overwhelmed. It is best to save the results intermittently and in your for-loop use a try/exception block to pluck out the ones throw `TimeoutError`. Once the for-loop is done, you can have a similar for-loop, but only for the missing ones.

**Comment by Flash-Of-Thunder** [comment]
Ah I see, yes. Thanks! 

And any wisdom on this `database is locked` error? After I added a line to refresh (remove) the cache sqlite file I still occasionally get a database is locked error.

**Comment by cheginit** [comment]
Technically, this should be related to interruptions when the cache is being written to the cache file. For example, when the code is at the step of writing to the cache and execution gets interrupted for some reason (like you might cancel it). It's difficult to reproduce, but I will try to investigate.
